import type { Metadata } from "next";
import { Orbitron } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar/Sidebar";

const orbitron = Orbitron({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${orbitron.variable}   antialiased`}>
        <div className="flex h-screen overflow-hidden p-8">
          <Sidebar />
          <main className="flex-1 p-8 ">{children}</main>
        </div>
      </body>
    </html>
  );
}
